### PR TITLE
Update ImiMMChangeLanguageObserver.php

### PR DESCRIPTION
**Pull request by Ainschy**
With these changes the extension runs under Contao 4.9.9 and MM2.2

### CODE REVIEW

**Comment by amenk** [comment]
Thank you very much!
Would you like to update the "tested until" info in the README as well?  Do you know until which version this is BC compatible?
Probably 3.5 will not work any more, but we do not need to care about that :D

**Comment by Ainschy** [comment]
I don't have Contao V4.4 with MM 2.1 at hand.

But querying the GLOBALS in the extension leads to an error that paralyzes the whole website.

I suggest you tag the changes as a separate version for MM2.2 and Contao 4.9

**Comment by zonky2** [comment]
see https://metamodels.readthedocs.io/de/latest/reference/interfaces/metamodels.html#beispiel  row #26 and #28

**Comment by amenk** [comment]
Thanks @Ainschy - Tagged 3.0.0

**Pull request merged**
